"""
enrich_processor.py – Transform raw scraped data into actionable intelligence.

This is Person 2's main entry point. It takes the output of
orchestrator.collect_raw_data() and adds LLM-generated insights.

Export:
  - enrich_raw_data(raw: dict) -> dict

Output schema (enriched fields added on top of raw):
  {
      # ── From Person 1 (raw, unchanged) ──────────────────────────────────
      "company_name":        str,
      "category":            str,
      "website":             str,
      "domain":              str | None,
      "overview":            { about_text, scale_indicators },
      "market_perception":   { recent_news_headlines, reviews },
      "competitors":         list,
      "brand_activity":      list,
      "events":              list,
      "decision_makers_raw": list,
      "contacts_raw":        list,

      # ── Generated by Person 2 (intelligence layer) ───────────────────────
      "company_overview":    str,   # #1  – LLM summary of about_text
      "market_position":     str,   # #2  – LLM analysis of news sentiment
      "competitor_mapping":  list,  # #3  – [{name, strength, gap}]
      "brand_activity_summary": list, # #4 – top 10 news items (raw)
      "event_footprint":     list,  # #5  – events list (raw)
      "strategic_watchouts": list,  # #6  – 3 LLM-generated risk bullets
      "decision_makers":     list,  # #7  – contacts enriched with outreach texts
      "opportunity_score":   int,   # #8  – 0-100 rule-based score
      "score_breakdown":     dict,  # #8b – component breakdown
      "outreach_generated":  bool,
      "_llm_backend":        str,   # "openai" | "ollama" | "mock"
  }
"""

import asyncio
import logging

from ..intelligence.competitor_analyzer import analyze_competitors
from ..intelligence.llm_client import get_llm
from ..intelligence.outreach_generator import (
    generate_email,
    generate_linkedin_message,
    generate_opportunity_angle,
)
from ..intelligence.overview_generator import generate_market_position, generate_overview
from ..intelligence.scorer import compute_opportunity_score, score_breakdown
from ..intelligence.watchout_generator import generate_watchouts

logger = logging.getLogger(__name__)


async def enrich_raw_data(raw: dict) -> dict:
    """
    Add LLM-generated insights to the raw scraped data dict.

    All LLM calls are wrapped in try/except so a single failure never
    crashes the whole pipeline.
    """
    company  = raw.get("company_name", "")
    category = raw.get("category", "")
    about    = raw.get("overview", {}).get("about_text", "")
    news     = raw.get("brand_activity", [])
    comps    = raw.get("competitors", [])
    events   = raw.get("events", [])
    contacts = raw.get("contacts_raw", [])

    logger.info(
        "[enrich] Starting enrichment for '%s' – news=%d comps=%d events=%d contacts=%d",
        company, len(news), len(comps), len(events), len(contacts),
    )

    # ── Run independent LLM tasks concurrently ───────────────────────────────
    (
        company_overview,
        market_position,
        competitor_mapping,
        watchouts,
    ) = await asyncio.gather(
        _safe(generate_overview(about),                              "overview",     company),
        _safe(generate_market_position(company, news),              "market_pos",   company),
        _safe(analyze_competitors(company, category, comps),        "competitors",  company),
        _safe(generate_watchouts(company, news, comps, events),     "watchouts",    company),
    )

    # ── Opportunity score (synchronous, no LLM) ──────────────────────────────
    opp_score     = compute_opportunity_score(news, events, comps, contacts)
    score_details = score_breakdown(news, events, comps, contacts)

    # ── Derive a shared opportunity angle for outreach ───────────────────────
    activity_summary = ", ".join(
        n.get("title", "") for n in news[:4] if n.get("title")
    )
    opportunity_angle = await _safe(
        generate_opportunity_angle(company, activity_summary),
        "opportunity_angle", company,
    ) or "helping brands amplify their marketing impact"

    # ── Generate personalised outreach for each named contact ────────────────
    enriched_contacts = []
    for contact in contacts:
        enriched = dict(contact)  # copy so we don't mutate the original
        name = contact.get("name")

        if name:
            li_msg, email_data = await asyncio.gather(
                _safe(
                    generate_linkedin_message(contact, company, news, opportunity_angle),
                    f"linkedin:{name}", company,
                ),
                _safe(
                    generate_email(contact, company, news, opportunity_angle),
                    f"email:{name}", company,
                ),
            )
            enriched["linkedin_message"] = li_msg or _no_llm_msg("LinkedIn message")
            enriched["email_subject"]    = (email_data or {}).get("subject", "")
            enriched["email_body"]       = (email_data or {}).get("body", "")
        else:
            enriched["linkedin_message"] = "Unable to generate: name not found"
            enriched["email_subject"]    = ""
            enriched["email_body"]       = ""

        enriched_contacts.append(enriched)

    # ── Assemble final enriched output ───────────────────────────────────────
    enriched_output = {
        **raw,  # keep all raw fields intact

        # Intelligence layer additions
        "company_overview":       company_overview  or _no_llm_msg("Company overview"),
        "market_position":        market_position   or _no_llm_msg("Market position"),
        "competitor_mapping":     competitor_mapping or [],
        "brand_activity_summary": news[:10],
        "event_footprint":        events,
        "strategic_watchouts":    watchouts         or [_no_llm_msg("Strategic watchouts")],
        "decision_makers":        enriched_contacts,
        "opportunity_score":      opp_score,
        "score_breakdown":        score_details,
        "outreach_generated":     bool(enriched_contacts),
        "_llm_backend":           get_llm().backend,
    }

    logger.info(
        "[enrich] Done for '%s' – score=%d backend=%s",
        company, opp_score, get_llm().backend,
    )
    return enriched_output


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

async def _safe(coro, label: str, company: str):
    """Await *coro*, log and return None on failure."""
    try:
        return await coro
    except Exception as exc:  # noqa: BLE001
        logger.error("[enrich] '%s' failed for '%s': %s", label, company, exc)
        return None


def _no_llm_msg(field: str) -> str:
    return f"[LLM not configured] {field} unavailable – set OPENAI_API_KEY or start Ollama."
